config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  get 'purchases/:list_id', to: 'purchases#index'
  resources :shopping_lists
  devise_for :users
  get 'pages/about_us', to: 'pages#about_us'
  root 'pages#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :shopping_list
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  has_many :purchases, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

    def user_not_authorized
      flash[:warning] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
  end

  def about_us
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
    authorize @purchases
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new(shopping_list_id: params['format'])
    @purchase.save
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(purchase_params)
    authorize @purchase

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render :show, status: :created, location: @purchase }
      else
        format.html { render :new }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
      authorize @purchase
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:title, :description, :buy)
    end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /shopping_lists
  # GET /shopping_lists.json
  def index
    @shopping_lists = ShoppingList.order(sort_column+' '+sort_direction).where('user_id = ?', pundit_user ? pundit_user.id : 0).paginate(:page => params[:page], :per_page => 10)
    authorize @shopping_lists
  end

  # GET /shopping_lists/1
  # GET /shopping_lists/1.json
  def show
    @purchases = Purchase.where('shopping_list_id = ?', params[:id]).order(sort_column+' '+sort_direction).paginate(:page => params[:page], :per_page => 5)
    @day_buy = Purchase.group_by_day(:updated_at).count
  end

  # GET /shopping_lists/new
  def new
    @shopping_list = ShoppingList.new
    authorize @shopping_list
  end

  # GET /shopping_lists/1/edit
  def edit
  end

  # POST /shopping_lists
  # POST /shopping_lists.json
  def create
    @shopping_list = ShoppingList.new(shopping_list_params)
    @shopping_list.user = current_user
    authorize @shopping_list

    respond_to do |format|
      if @shopping_list.save
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_list }
      else
        format.html { render :new }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_lists/1
  # PATCH/PUT /shopping_lists/1.json
  def update
    respond_to do |format|
      if @shopping_list.update(shopping_list_params)
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_list }
      else
        format.html { render :edit }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_lists/1
  # DELETE /shopping_lists/1.json
  def destroy
    @shopping_list.destroy
    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Shopping list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_list
      @shopping_list = ShoppingList.find(params[:id])
      authorize @shopping_list
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_list_params
      params.require(:shopping_list).permit(:title, :description)
    end

    def sort_column
      (ShoppingList.column_names.include?(params[:sort]) or Purchase.column_names.include?(params[:sort])) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Myapp"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to "Myapp", root_path, :class => 'navbar-brand'
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "About us", pages_about_us_path
              li= link_to "Shopping lists", shopping_lists_path
            ul.nav.navbar-nav.pull-right
              - if user_signed_in?
                li.email= current_user.email
                li= link_to 'Log out', destroy_user_session_path, method: :delete
              - else
                li= link_to 'Log In', new_user_session_path
                li= link_to 'Sign Up', new_user_registration_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3

      footer
        p &copy; Company 2019

app/views/pages/about_us.html.slim
h1 Pages#about_us
p Find me in app/views/pages/about_us.html.slim
= @params

app/views/pages/hello.html.slim
h1 Pages#hello
p Find me in app/views/pages/hello.html.slim

app/views/purchases/_form.html.slim
= form_for @purchase, html: { class: "form form-horizontal purchase" } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
    = f.error_span(:title)
  .form-group
    = f.label :description, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :description, :class => 'form-control'
    = f.error_span(:description)
  .form-group
    = f.label :buy, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select :buy, not: 0, ok: 1
    = f.error_span(:buy)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), '/shopping_lists/'+@purchase.shopping_list_id.to_s, :class => 'btn btn-default'

app/views/purchases/edit.html.slim
- model_class = Purchase
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/purchases/index.html.slim
- model_class = Purchase
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:buy)
      th= model_class.human_attribute_name(:shopping_list_id)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @purchases.each do |purchase|
      tr
        td= link_to purchase.id, purchase_path(purchase)
        td= purchase.title
        td= purchase.description
        td= purchase.buy
        td= purchase.shopping_list_id
        td=l purchase.created_at
        td
          = link_to t('.show', :default => t("helpers.links.show")), purchase_path(purchase), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_purchase_path(purchase), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), purchase_path(purchase), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_purchase_path, :class => 'btn btn-primary'

app/views/purchases/new.html.slim
- model_class = Purchase
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/purchases/show.html.slim
- model_class = Purchase
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @purchase.title
p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @purchase.description
p
  strong= model_class.human_attribute_name(:buy) + ':'
  br
  = @purchase.buy

= link_to t('.back', :default => t("helpers.links.back")), shopping_list_path(@purchase.shopping_list_id), :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_purchase_path(@purchase), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), purchase_path(@purchase), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/shopping_lists/_form.html.slim
= form_for @shopping_list, html: { class: "form form-horizontal shopping_list" } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
    = f.error_span(:title)
  .form-group
    = f.label :description, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :description, :class => 'form-control'
    = f.error_span(:description)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), shopping_lists_path, :class => 'btn'

app/views/shopping_lists/edit.html.slim
- model_class = ShoppingList
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/shopping_lists/index.html.slim
- model_class = ShoppingList
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= sortable "title", model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:description)
      th= sortable "created_at", model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @shopping_lists.each do |shopping_list|
      tr
        td= link_to shopping_list.title, shopping_list_path(shopping_list)
        td= shopping_list.description
        td= shopping_list.created_at.strftime("%B %e, %Y")
        td
          = link_to t('.show', :default => t("helpers.links.show")), shopping_list_path(shopping_list), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_shopping_list_path(shopping_list), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), shopping_list_path(shopping_list), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
div= will_paginate @shopping_lists
= link_to t('.new', :default => t("helpers.links.new")), new_shopping_list_path, :class => 'btn btn-primary'

app/views/shopping_lists/new.html.slim
- model_class = ShoppingList
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/shopping_lists/show.html.slim
- model_class = ShoppingList
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

= line_chart Purchase.where('shopping_list_id = ?', @shopping_list.id).group_by_day_of_month(:updated_at).count

p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @shopping_list.title
p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @shopping_list.description

= link_to t('.back', :default => t("helpers.links.back")), shopping_lists_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_shopping_list_path(@shopping_list), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), shopping_list_path(@shopping_list), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

- model_class_p = Purchase
table.table.table-striped
  thead
    tr
      th= sortable "title", model_class_p.human_attribute_name(:title)
      th= model_class_p.human_attribute_name(:description)
      th= sortable "buy", model_class_p.human_attribute_name(:buy)
      th= sortable "created_at", model_class_p.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @purchases.each do |purchase|
      tr
        td= link_to purchase.title, purchase_path(purchase)
        td= purchase.description
        td= purchase.buy ? 'ok' : 'not'
        td= purchase.created_at.strftime("%B %e, %Y")
        td
          = link_to t('.show', :default => t("helpers.links.show")), purchase_path(purchase), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_purchase_path(purchase), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), purchase_path(purchase), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
div= will_paginate @purchases
= link_to t('.new', :default => t("helpers.links.new")), new_purchase_path(@shopping_list), :class => 'btn btn-primary'